[general]
import = ["~/.config/alacritty/catppuccin_frappe.toml"]

[env]
TERM = "xterm-256color"

[window]
padding.x = 10
padding.y = 10
decorations = "Buttonless"
opacity = 0.7
blur = false

[font]
normal.family = "MesloLGM Nerd Font Propo"
size = 12

[colors]
transparent_background_colors = true

[selection]
save_to_clipboard =  true
